dependencies {

    implementation(elytraModpackVersion.gtnhdev("Forgelin"))
    implementation(elytraModpackVersion.gtnhdev("GT5-Unofficial"))
    implementation(elytraModpackVersion.gtnhdev("NewHorizonsCoreMod"))
    implementation(elytraModpackVersion.gtnhdev("Galaxy-Space-GTNH"))
    implementation(elytraModpackVersion.gtnhdev("Avaritia"))
    implementation(elytraModpackVersion.gtnhdev("Avaritiaddons"))
    implementation(elytraModpackVersion.gtnhdev("Universal-Singularities"))
    implementation(elytraModpackVersion.gtnhdev("CodeChickenCore"))

    compileOnly("com.github.GTNewHorizons:TinkersGregworks:GTNH-1.0.27:dev") { transitive = false }

    runtimeOnlyNonPublishable(elytraModpackVersion.gtnhdev("BlockRenderer6343")) { transitive = false }
}
