package vis.rhynia.nova.common.material.generation

import buildcraft.api.core.StackKey.fluid
import gregtech.api.enums.FluidState
import gregtech.api.enums.OrePrefixes
import gregtech.api.fluid.GTFluidFactory
import net.minecraftforge.fluids.Fluid
import net.minecraftforge.fluids.FluidRegistry
import vis.rhynia.nova.Log
import vis.rhynia.nova.api.interfaces.Loader
import vis.rhynia.nova.common.item.container.NovaGeneratedItem

object SimpleMaterialLoader : Loader {
  override fun load() {
    Log.info("Registering materials...")
    val time1 = System.currentTimeMillis()
    materialSet.forEach {
      Log.info("Loading material: ${it.id}: ${it.internalName}")
      generateFluid(it)
      generateMetaItem(it)
      materialMap[it.id] = it
    }
    Log.info("Generated ${materialMap.size} materials in ${System.currentTimeMillis() - time1}ms")
  }

  val materialSet = mutableSetOf<SimpleMaterial>()
  val materialMap = mutableMapOf<Short, SimpleMaterial>()
  val itemMap = mutableMapOf<OrePrefixes, NovaGeneratedItem>()
  val fluidMap = mutableMapOf<SimpleMaterial, MutableMap<FluidState, Fluid>>()

  private fun generateFluid(material: SimpleMaterial) {
    if (!material.flagFluid) return
    material.fluidStateMap.forEach { (state, info) ->
      val (name, temperature) = info
      var fluid: Fluid
      if (FluidRegistry.isFluidRegistered(name)) {
        Log.warn("Fluid $name is already registered!")
        fluid = FluidRegistry.getFluid(name)
      } else {
        GTFluidFactory.builder(name)
            .withLocalizedName(material.displayName)
            .withStateAndTemperature(state, temperature)
            .withTextureName("autogenerated")
            .withColorRGBA(material.color)
            .buildAndRegister()
            .asFluid()
            .let { fluid = it }
        Log.info("Generated fluid ${null}")
      }
      fluidMap[material]?.let { it[state] = fluid }
          ?: run { fluidMap[material] = mutableMapOf(state to fluid) }
    }
  }

  private fun generateMetaItem(material: SimpleMaterial) {
    material.getFinalOrePrefixes().forEach {
      itemMap[it] = NovaGeneratedItem(it)
      Log.info("Generated item for ${material.internalName}: ${it.name}")
    }
  }
}
